### ISSUE TITLE
Remove Mixin if unneeded

### ISSUE THREAD

**Issue by pkstDev** [Archasmiel/fabric_thaumcraft-rewrited#2]
Seems that the ThaumcraftMixin is changed directly from the ExampleMixin and does literally nothing.
If you don't need the hacky asm magic, you can just remove it, since it's not required.
You can add one (or more) mixin class again anyway.

**Comment by Archasmiel** [comment]
Thank you, I'm actually not gonna use mixins in near future)
So, deleted ThaumcraftMixin from project for now.

**Comment by pkstDev** [comment]
No problem, it's just one small thing to slim the mod
